[package]
name = "caisse_enregistreuse"
version = "0.1.0"
edition = "2024"

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master", features = ["api-custom"] }

[lib]
crate-type = ["cdylib"] # dynamic C library
